version: '3.8'

services:
  dash:
    build: .
    container_name: erp
    restart: on-failure
    env_file: .env
    ports:
    - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dash.tls=true"
      - "traefik.http.routers.dash.rule=Host(`dash.docker.localhost`)"
      - "traefik.http.services.dash.loadbalancer.server.port=8000"  # Porta interna
      - "estatcamp.url=https://dash.docker.localhost"
    networks:
      - proxy


  reverse-proxy:
    image: traefik:v2.3
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/.certs:/etc/certs:ro
      - ${HOME}/.traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${HOME}/.traefik/config.yml:/etc/traefik/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"
    networks:
      - proxy

networks:
  proxy:
    external: true


